// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzqAnYAkNMCSFMqGq0KfSdHou4OvuQWXY',
    appId: '1:998083994959:web:83d24f0a24cd27fa4cd13a',
    messagingSenderId: '998083994959',
    projectId: 'ulearning-app-77984',
    authDomain: 'ulearning-app-77984.firebaseapp.com',
    storageBucket: 'ulearning-app-77984.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcWU0Ij1w811s94xkUgOWVLtJX4ay_M4',
    appId: '1:998083994959:android:d5dddd3c4470b4aa4cd13a',
    messagingSenderId: '998083994959',
    projectId: 'ulearning-app-77984',
    storageBucket: 'ulearning-app-77984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBOD5yKP_dd2jvDBqKm968w4SpaWh983I',
    appId: '1:998083994959:ios:c3a25b0462b2d2804cd13a',
    messagingSenderId: '998083994959',
    projectId: 'ulearning-app-77984',
    storageBucket: 'ulearning-app-77984.appspot.com',
    iosBundleId: 'com.ngocdm.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBOD5yKP_dd2jvDBqKm968w4SpaWh983I',
    appId: '1:998083994959:ios:48472cbd14d90c7f4cd13a',
    messagingSenderId: '998083994959',
    projectId: 'ulearning-app-77984',
    storageBucket: 'ulearning-app-77984.appspot.com',
    iosBundleId: 'com.example.ulearningApp.RunnerTests',
  );
}
