library values;

import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:resume/common/routes/routes.dart';
import 'package:resume/common/widgets/nav_item.dart';
import 'package:resume/common/widgets/project_item.dart';
part 'colors.dart';
part 'borders.dart';
part 'images.dart';
part 'sizes.dart';
part 'strings.dart';
part 'styles.dart';
part 'gradients.dart';
part 'decoration.dart';
part 'data.dart';
part 'docs.dart';
part 'animations.dart';
